-- SCRIPT COMPLETO PARA AGREGAR TODAS LAS RECETAS A LA BASE DE DATOS
-- PARTE 1: Ingredientes y Recetas Principales

-- Primero agregamos todos los ingredientes necesarios
INSERT INTO ingredientes (nombre, unidad_base, categoria) VALUES
-- Proteínas
('Suprema', 'g', 'proteina'),
('Carne en cubos', 'g', 'proteina'),
('Carne entera', 'g', 'proteina'),
('Carne picada o en cubos', 'g', 'proteina'),
('Carne de cerdo', 'g', 'proteina'),
('Carne picada', 'g', 'proteina'),
('Milanesa de carne', 'g', 'proteina'),
('Milanesa de pescado', 'g', 'proteina'),
('Milanesa de pollo', 'g', 'proteina'),
('Suprema de pollo', 'g', 'proteina'),
('Pollo suprema', 'g', 'proteina'),
('Pescado', 'g', 'proteina'),
('Atún', 'g', 'proteina'),

-- Cereales y harinas
('Avena', 'g', 'cereal'),
('Arroz', 'g', 'cereal'),
('Fideos', 'g', 'cereal'),
('Lentejas', 'g', 'cereal'),
('Polenta', 'g', 'cereal'),
('Harina de maíz', 'g', 'cereal'),
('Harina de trigo', 'g', 'cereal'),
('Harina', 'g', 'cereal'),
('Harina de mijo', 'g', 'cereal'),
('Almidón de maíz', 'g', 'cereal'),
('Pan rallado', 'g', 'cereal'),
('Polvo de hornear', 'g', 'cereal'),
('Levadura seca', 'g', 'cereal'),
('Cebada instantánea', 'g', 'cereal'),

-- Verduras
('Zanahoria', 'g', 'verdura'),
('Cebolla', 'g', 'verdura'),
('Morrón', 'g', 'verdura'),
('Papa', 'g', 'verdura'),
('Boniato', 'g', 'verdura'),
('Zapallo/calabaza', 'g', 'verdura'),
('Zapallo', 'g', 'verdura'),
('Calabaza', 'g', 'verdura'),
('Zapallito', 'g', 'verdura'),
('Berenjena', 'g', 'verdura'),
('Choclo', 'g', 'verdura'),
('Arvejas', 'g', 'verdura'),
('Porotos manteca', 'g', 'verdura'),
('Espinaca', 'g', 'verdura'),
('Acelga', 'g', 'verdura'),
('Brócoli fresco', 'g', 'verdura'),
('Repollo', 'g', 'verdura'),
('Tomate', 'g', 'verdura'),
('Puerro', 'g', 'verdura'),
('Apio', 'g', 'verdura'),
('Chaucha', 'g', 'verdura'),
('Lechuga', 'g', 'verdura'),
('Remolacha', 'g', 'verdura'),

-- Frutas
('Banana', 'g', 'fruta'),
('Naranja', 'ml', 'fruta'),
('Manzana rallada', 'g', 'fruta'),
('Fruta', 'g', 'fruta'),
('Naranja con cáscara', 'g', 'fruta'),

-- Lácteos
('Queso rallado', 'g', 'lacteo'),
('Queso fresco rallado', 'g', 'lacteo'),
('Queso Danbo, Cuartirolo, Gouda o Port Salut', 'g', 'lacteo'),
('Ricota', 'g', 'lacteo'),
('Dulce de leche', 'g', 'lacteo'),
('Leche fluida', 'ml', 'lacteo'),
('Leche en polvo', 'g', 'lacteo'),

-- Condimentos y especias
('Sal', 'g', 'condimento'),
('Aceite', 'ml', 'condimento'),
('Aceite (asadera)', 'ml', 'condimento'),
('Aceite (asadera)', 'g', 'condimento'),
('Ajo', 'g', 'condimento'),
('Perejil', 'g', 'condimento'),
('Hierbas (orégano, albahaca, tomillo, perejil)', 'g', 'condimento'),
('Mix de verdes (perejil, ciboulette)', 'g', 'condimento'),
('Orégano', 'g', 'condimento'),
('Pimentón', 'g', 'condimento'),
('Nuez moscada', 'g', 'condimento'),
('Tomillo', 'g', 'condimento'),
('Albahaca', 'g', 'condimento'),
('Ciboulette', 'g', 'condimento'),
('Canela', 'g', 'condimento'),
('Canela en rama', 'c/n', 'condimento'),
('Cúrcuma', 'g', 'condimento'),
('Laurel', 'hoja', 'condimento'),
('Apio', 'g', 'condimento'),
('Puerro', 'g', 'verdura'),
('Hierbas frescas', 'g', 'condimento'),
('Hierbas aromáticas', 'g', 'condimento'),
('Hierbas aromáticas secas', 'g', 'condimento'),
('Hierbas aromáticas frescas', 'g', 'condimento'),
('Ralladura de limón o naranja', 'c/n', 'condimento'),
('Ralladura de limón', 'c/n', 'condimento'),
('Ralladura de naranja', 'unidad', 'condimento'),
('Ralladura de limón', 'g', 'condimento'),
('Ralladura de naranja', 'unidad', 'condimento'),
('Cáscara de naranja', 'c/n', 'condimento'),
('Jengibre fresco', 'g', 'condimento'),

-- Otros ingredientes
('Pulpa de tomate', 'ml', 'otro'),
('Pulpa de tomate', 'g', 'otro'),
('Agua', 'ml', 'otro'),
('Agua tibia', 'ml', 'otro'),
('Agua hervida y entibiada', 'ml', 'otro'),
('Agua de cocción', 'ml', 'otro'),
('Azúcar', 'g', 'otro'),
('Vainilla', 'ml', 'otro'),
('Vainilla', 'g', 'otro'),
('Cocoa', 'g', 'otro'),
('Cacao', 'g', 'otro'),
('Coco rallado', 'g', 'otro'),
('Coco', 'g', 'otro'),
('Yemas', 'g', 'otro'),
('Huevo', 'g', 'otro'),
('Huevos', 'unidad', 'otro'),
('Huevo', 'unidad', 'otro'),
('Huevos', 'unid.', 'otro'),
('Huevo', 'unid.', 'otro'),
('Dulce de membrillo', 'g', 'otro'),
('Pasas de uva', 'g', 'otro'),
('Semillas de lino', 'g', 'otro'),
('Semillas de sésamo', 'g', 'otro'),
('Semillas de girasol', 'g', 'otro'),
('Maní sin sal', 'g', 'otro'),
('Jugo de limón', 'ml', 'otro'),
('Jugo de naranja', 'unidad', 'otro'),
('Jugo de limón', 'unidad', 'otro'),
('Vinagre/jugo de limón', 'ml', 'otro'),
('Vinagre', 'ml', 'otro'),
('Mayonesa', 'g', 'otro'),
('Mayonesa vegetal', 'g', 'otro'),
('Salsa blanca', 'porción', 'otro'),
('Salsa blanca liviana', 'porción', 'otro'),
('Salsa Blanca Liviana', 'porción', 'otro'),
('Puré en escama', 'g', 'otro'),
('Verdura de estación', 'g', 'otro'),
('Vegetales', 'g', 'otro'),
('Frutos secos deshidratados', 'g', 'otro'),
('Frutas deshidratadas', 'g', 'otro'),
('Porotos negros crudos', 'g', 'otro'),
('Garbanzos', 'g', 'otro'),
('Salvado de trigo', 'g', 'otro'),
('Rúcula fresca', 'g', 'otro'),
('Rúcula congelada', 'g', 'otro'),
('Zapallo Cabutia', 'g', 'otro'),
('Leche en fluída', 'ml', 'otro'),
('Leche fuída', 'ml', 'otro'),
('Leche fuída con cocoa', 'ml', 'otro'),
('Leche fuída con cebada instantánea', 'ml', 'otro'),
('Leche fuída con vainilla', 'ml', 'otro'),
('Leche en polvo con cocoa', 'ml', 'otro'),
('Leche en polvo con cebada instantánea', 'ml', 'otro'),
('Leche en polvo con vainilla', 'ml', 'otro'),
('Aceite', 'cc', 'otro'),
('Aceite', 'g', 'otro'),
('Condimentos (pimentón, nuez moscada)', 'g', 'otro'),
('Hierbas o condimentos', 'c/n', 'otro')
ON CONFLICT (nombre) DO NOTHING;

-- Agregamos todas las recetas
INSERT INTO recetas (titulo, categoria, descripcion) VALUES
-- Almuerzos y cenas
('Bocaditos de pollo', 'almuerzo', 'Bocaditos de pollo con avena y hierbas'),
('Budín de pescado', 'almuerzo', 'Budín de pescado con verduras'),
('Carbonada criolla', 'almuerzo', 'Carbonada criolla tradicional'),
('Carne a la portuguesa', 'almuerzo', 'Carne a la portuguesa con verduras'),
('Cazuela de lentejas', 'almuerzo', 'Cazuela de lentejas con carne'),
('Chop suey de cerdo', 'almuerzo', 'Chop suey de cerdo con verduras'),
('Chupín de pescado y verduras', 'almuerzo', 'Chupín de pescado con verduras'),
('Croquetas de atún y papas', 'almuerzo', 'Croquetas de atún con papas'),
('Ensalada completa de pollo', 'almuerzo', 'Ensalada completa con pollo'),
('Ensalada completa de atún', 'almuerzo', 'Ensalada completa con atún'),
('Hamburguesa de pescado', 'almuerzo', 'Hamburguesa de pescado'),
('Lasaña', 'almuerzo', 'Lasaña de acelga y carne'),
('Pan de Carne / Hamburguesa', 'almuerzo', 'Pan de carne o hamburguesa'),
('Pasta sorpresa', 'almuerzo', 'Pasta sorpresa con pollo y brócoli'),
('Pasta con verdusalsa', 'almuerzo', 'Pasta con verdusalsa'),
('Pastel de carne y papa', 'almuerzo', 'Pastel de carne con papa'),
('Pollo colorido', 'almuerzo', 'Pollo colorido con verduras'),
('Pastel de carne y berenjenas', 'almuerzo', 'Pastel de carne con berenjenas'),
('Pollo con salsa blanca y verduras', 'almuerzo', 'Pollo con salsa blanca'),
('Torta de carne y vegetales', 'almuerzo', 'Torta de carne con vegetales'),
('Tortilla de papa, vegetales y pollo', 'almuerzo', 'Tortilla de papa con pollo'),
('Torta de atún', 'almuerzo', 'Torta de atún'),
('Arroz', 'almuerzo', 'Arroz básico'),
('Fideos', 'almuerzo', 'Fideos básicos'),
('Arroz con vegetales salteados', 'almuerzo', 'Arroz con vegetales salteados'),
('Arroz amarillo', 'almuerzo', 'Arroz amarillo con cúrcuma'),
('Ensalada de vegetales', 'almuerzo', 'Ensalada de vegetales'),
('Ensalada jardinera', 'almuerzo', 'Ensalada jardinera'),
('Ensalada primavera', 'almuerzo', 'Ensalada primavera'),
('Ensalada de leguminosas y vegetales', 'almuerzo', 'Ensalada de leguminosas'),
('Papas al natural', 'almuerzo', 'Papas al natural'),
('Puré de papas', 'almuerzo', 'Puré de papas'),
('Puré triple', 'almuerzo', 'Puré triple de papas, zapallo y zanahoria'),
('Puré de papas instantáneo', 'almuerzo', 'Puré de papas instantáneo'),
('Hortalizas asadas', 'almuerzo', 'Hortalizas asadas'),
('Salsa blanca liviana', 'almuerzo', 'Salsa blanca liviana'),
('Arroz plato principal', 'almuerzo', 'Arroz como plato principal'),
('Fideos plato principal', 'almuerzo', 'Fideos como plato principal'),

-- Postres
('Arroz con leche', 'postre', 'Arroz con leche'),
('Crema de naranja', 'postre', 'Crema de naranja'),
('Crema de vainilla', 'postre', 'Crema de vainilla'),
('Budín de zapallo y coco', 'postre', 'Budín de zapallo y coco'),
('Budín de harina de maíz', 'postre', 'Budín de harina de maíz'),

-- Recetas base
('Polenta/plato principal', 'receta_base', 'Polenta como plato principal'),
('Masa básica para tortas', 'receta_base', 'Masa básica para tortas'),
('Filloas', 'receta_base', 'Filloas'),

-- Desayunos y meriendas
('Brownie de porotos negros', 'desayuno', 'Brownie de porotos negros'),
('Budín de banana', 'desayuno', 'Budín de banana'),
('Fainá de zanahoria y queso', 'desayuno', 'Fainá de zanahoria y queso'),
('Pasta frola', 'desayuno', 'Pasta frola'),
('Torta básica de vainilla', 'desayuno', 'Torta básica de vainilla'),
('Torta de calabaza', 'desayuno', 'Torta de calabaza'),
('Torta de naranja', 'desayuno', 'Torta de naranja'),
('Pan casero', 'desayuno', 'Pan casero'),
('Pan de calabaza', 'desayuno', 'Pan de calabaza'),
('Scones de queso', 'desayuno', 'Scones de queso'),
('Scones dulces', 'desayuno', 'Scones dulces'),
('Hummus', 'desayuno', 'Hummus'),
('Untable de ricota', 'desayuno', 'Untable de ricota'),
('Untable de zanahoria', 'desayuno', 'Untable de zanahoria'),
('Galletas de avena y pasas', 'desayuno', 'Galletas de avena y pasas'),
('Galletas de avena y queso', 'desayuno', 'Galletas de avena y queso'),
('Galletitas cítricas', 'desayuno', 'Galletitas cítricas'),
('Ojitos caseros', 'desayuno', 'Ojitos caseros'),
('Alfajores de maicena', 'desayuno', 'Alfajores de maicena'),
('Barra de cereales', 'desayuno', 'Barra de cereales'),
('Mix de frutos secos', 'desayuno', 'Mix de frutos secos'),
('Crema de vainilla', 'desayuno', 'Crema de vainilla'),
('Licuado de leche y fruta', 'desayuno', 'Licuado de leche y fruta'),
('Ojitos de mijo', 'desayuno', 'Ojitos de mijo'),

-- Copa de leche
('Leche fluida con cocoa', 'copa_leche', 'Leche fluida con cocoa'),
('Leche fluida con cebada instantánea', 'copa_leche', 'Leche fluida con cebada instantánea'),
('Leche fluida con vainilla', 'copa_leche', 'Leche fluida con vainilla'),
('Leche en polvo con cocoa', 'copa_leche', 'Leche en polvo con cocoa'),
('Leche en polvo con cebada instantánea', 'copa_leche', 'Leche en polvo con cebada instantánea'),
('Leche en polvo con vainilla', 'copa_leche', 'Leche en polvo con vainilla')
ON CONFLICT DO NOTHING;

-- Verificamos lo agregado hasta ahora
SELECT 'Ingredientes agregados' as tipo, COUNT(*) as cantidad FROM ingredientes;
SELECT 'Recetas agregadas' as tipo, COUNT(*) as cantidad FROM recetas;
SELECT 'Recetas por categoría' as tipo, categoria, COUNT(*) as cantidad FROM recetas GROUP BY categoria ORDER BY categoria;
